const gridTemplateColumns = [
  "dd-grid-cols-1",
  "dd-grid-cols-2",
  "dd-grid-cols-3",
  "dd-grid-cols-4",
  "dd-grid-cols-5",
  "dd-grid-cols-6",
  "dd-grid-cols-7",
  "dd-grid-cols-8",
  "dd-grid-cols-9",
  "dd-grid-cols-10",
  "dd-grid-cols-11",
  "dd-grid-cols-12",
  "dd-grid-cols-none",
];
