const backgroundBlendMode = [
  "dd-bg-blend-normal",
  "dd-bg-blend-multiply",
  "dd-bg-blend-screen",
  "dd-bg-blend-overlay",
  "dd-bg-blend-darken",
  "dd-bg-blend-lighten",
  "dd-bg-blend-color-dodge",
  "dd-bg-blend-hard-light",
  "dd-bg-blend-soft-light",
  "dd-bg-blend-difference",
  "dd-bg-blend-exclusion",
  "dd-bg-blend-hue",
  "dd-bg-blend-saturation",
  "dd-bg-blend-color",
  "dd-bg-blend-luminosity",
];
