const lineHeight = [
  "dd-leading-3",
  "dd-leading-4",
  "dd-leading-5",
  "dd-leading-6",
  "dd-leading-7",
  "dd-leading-8",
  "dd-leading-9",
  "dd-leading-10",
  "dd-leading-none",
  "dd-leading-tight",
  "dd-leading-snug",
  "dd-leading-normal",
  "dd-leading-relexed",
  "dd-leading-loose",
];
