const typography =[
    "dd-text-xs",
    "dd-text-sm",
    "dd-text-base",
    "dd-text-lg",
    "dd-text-xl",
    "dd-text-2xl",
    "dd-text-3xl",
    "dd-text-4xl",
    "dd-text-5xl",
    "dd-text-6xl",
    "dd-text-7xl",
    "dd-text-8xl",
    "dd-text-9xl",
//font weights 
    "dd-font-thin",
    "dd-font-extralight",
    "dd-font-light",
    "dd-font-normal",
    "dd-font-medium",
    "dd-font-semibold",
    "dd-font-bold",
    "dd-font-extrabold",
    "dd-font-black",
]