const scrollPadding = [
  "dd-scroll-p-0",
  "dd-scroll-px-0",
  "dd-scroll-py-0",
  "dd-scroll-ps-0",
  "dd-scroll-pt-0",
  "dd-scroll-pr-0",
  "dd-scroll-pb-0",
  "dd-scroll-pl-0",

  "dd-scroll-p-px",
  "dd-scroll-px-px",
  "dd-scroll-py-px",
  "dd-scroll-ps-px",
  "dd-scroll-pt-px",
  "dd-scroll-pr-px",
  "dd-scroll-pb-px",
  "dd-scroll-pl-px",

  "dd-scroll-p-0.5",
  "dd-scroll-px-0.5",
  "dd-scroll-py-0.5",
  "dd-scroll-ps-0.5",
  "dd-scroll-pt-0.5",
  "dd-scroll-pr-0.5",
  "dd-scroll-pb-0.5",
  "dd-scroll-pl-0.5",

  "dd-scroll-p-1",
  "dd-scroll-px-1",
  "dd-scroll-py-1",
  "dd-scroll-ps-1",
  "dd-scroll-pt-1",
  "dd-scroll-pr-1",
  "dd-scroll-pb-1",
  "dd-scroll-pl-1",

  "dd-scroll-p-1.5",
  "dd-scroll-px-1.5",
  "dd-scroll-py-1.5",
  "dd-scroll-ps-1.5",
  "dd-scroll-pt-1.5",
  "dd-scroll-pr-1.5",
  "dd-scroll-pb-1.5",
  "dd-scroll-pl-1.5",

  "dd-scroll-p-2",
  "dd-scroll-px-2",
  "dd-scroll-py-2",
  "dd-scroll-ps-2",
  "dd-scroll-pt-2",
  "dd-scroll-pr-2",
  "dd-scroll-pb-2",
  "dd-scroll-pl-2",

  "dd-scroll-p-2.5",
  "dd-scroll-px-2.5",
  "dd-scroll-py-2.5",
  "dd-scroll-ps-2.5",
  "dd-scroll-pt-2.5",
  "dd-scroll-pr-2.5",
  "dd-scroll-pb-2.5",
  "dd-scroll-pl-2.5",

  "dd-scroll-p-3",
  "dd-scroll-px-3",
  "dd-scroll-py-3",
  "dd-scroll-ps-3",
  "dd-scroll-pt-3",
  "dd-scroll-pr-3",
  "dd-scroll-pb-3",
  "dd-scroll-pl-3",

  "dd-scroll-p-3.5",
  "dd-scroll-px-3.5",
  "dd-scroll-py-3.5",
  "dd-scroll-ps-3.5",
  "dd-scroll-pt-3.5",
  "dd-scroll-pr-3.5",
  "dd-scroll-pb-3.5",
  "dd-scroll-pl-3.5",

  "dd-scroll-p-4",
  "dd-scroll-px-4",
  "dd-scroll-py-4",
  "dd-scroll-ps-4",
  "dd-scroll-pt-4",
  "dd-scroll-pr-4",
  "dd-scroll-pb-4",
  "dd-scroll-pl-4",

  "dd-scroll-p-5",
  "dd-scroll-px-5",
  "dd-scroll-py-5",
  "dd-scroll-ps-5",
  "dd-scroll-pt-5",
  "dd-scroll-pr-5",
  "dd-scroll-pb-5",
  "dd-scroll-pl-5",

  "dd-scroll-p-6",
  "dd-scroll-px-6",
  "dd-scroll-py-6",
  "dd-scroll-ps-6",
  "dd-scroll-pt-6",
  "dd-scroll-pr-6",
  "dd-scroll-pb-6",
  "dd-scroll-pl-6",

  "dd-scroll-p-7",
  "dd-scroll-px-7",
  "dd-scroll-py-7",
  "dd-scroll-ps-7",
  "dd-scroll-pt-7",
  "dd-scroll-pr-7",
  "dd-scroll-pb-7",
  "dd-scroll-pl-7",

  "dd-scroll-p-8",
  "dd-scroll-px-8",
  "dd-scroll-py-8",
  "dd-scroll-ps-8",
  "dd-scroll-pt-8",
  "dd-scroll-pr-8",
  "dd-scroll-pb-8",
  "dd-scroll-pl-8",

  "dd-scroll-p-9",
  "dd-scroll-px-9",
  "dd-scroll-py-9",
  "dd-scroll-ps-9",
  "dd-scroll-pt-9",
  "dd-scroll-pr-9",
  "dd-scroll-pb-9",
  "dd-scroll-pl-9",

  "dd-scroll-p-10",
  "dd-scroll-px-10",
  "dd-scroll-py-10",
  "dd-scroll-ps-10",
  "dd-scroll-pt-10",
  "dd-scroll-pr-10",
  "dd-scroll-pb-10",
  "dd-scroll-pl-10",

  "dd-scroll-p-11",
  "dd-scroll-px-11",
  "dd-scroll-py-11",
  "dd-scroll-ps-11",
  "dd-scroll-pt-11",
  "dd-scroll-pr-11",
  "dd-scroll-pb-11",
  "dd-scroll-pl-11",

  "dd-scroll-p-12",
  "dd-scroll-px-12",
  "dd-scroll-py-12",
  "dd-scroll-ps-12",
  "dd-scroll-pt-12",
  "dd-scroll-pr-12",
  "dd-scroll-pb-12",
  "dd-scroll-pl-12",

  "dd-scroll-p-14",
  "dd-scroll-px-14",
  "dd-scroll-py-14",
  "dd-scroll-ps-14",
  "dd-scroll-pt-14",
  "dd-scroll-pr-14",
  "dd-scroll-pb-14",
  "dd-scroll-pl-14",

  "dd-scroll-p-16",
  "dd-scroll-px-16",
  "dd-scroll-py-16",
  "dd-scroll-ps-16",
  "dd-scroll-pt-16",
  "dd-scroll-pr-16",
  "dd-scroll-pb-16",
  "dd-scroll-pl-16",

  "dd-scroll-p-20",
  "dd-scroll-px-20",
  "dd-scroll-py-20",
  "dd-scroll-ps-20",
  "dd-scroll-pt-20",
  "dd-scroll-pr-20",
  "dd-scroll-pb-20",
  "dd-scroll-pl-20",

  "dd-scroll-p-24",
  "dd-scroll-px-24",
  "dd-scroll-py-24",
  "dd-scroll-ps-24",
  "dd-scroll-pt-24",
  "dd-scroll-pr-24",
  "dd-scroll-pb-24",
  "dd-scroll-pl-24",

  "dd-scroll-p-28",
  "dd-scroll-px-28",
  "dd-scroll-py-28",
  "dd-scroll-ps-28",
  "dd-scroll-pt-28",
  "dd-scroll-pr-28",
  "dd-scroll-pb-28",
  "dd-scroll-pl-28",

  "dd-scroll-p-32",
  "dd-scroll-px-32",
  "dd-scroll-py-32",
  "dd-scroll-ps-32",
  "dd-scroll-pt-32",
  "dd-scroll-pr-32",
  "dd-scroll-pb-32",
  "dd-scroll-pl-32",

  "dd-scroll-p-36",
  "dd-scroll-px-36",
  "dd-scroll-py-36",
  "dd-scroll-ps-36",
  "dd-scroll-pt-36",
  "dd-scroll-pr-36",
  "dd-scroll-pb-36",
  "dd-scroll-pl-36",

  "dd-scroll-p-40",
  "dd-scroll-px-40",
  "dd-scroll-py-40",
  "dd-scroll-ps-40",
  "dd-scroll-pt-40",
  "dd-scroll-pr-40",
  "dd-scroll-pb-40",
  "dd-scroll-pl-40",

  "dd-scroll-p-44",
  "dd-scroll-px-44",
  "dd-scroll-py-44",
  "dd-scroll-ps-44",
  "dd-scroll-pt-44",
  "dd-scroll-pr-44",
  "dd-scroll-pb-44",
  "dd-scroll-pl-44",

  "dd-scroll-p-48",
  "dd-scroll-px-48",
  "dd-scroll-py-48",
  "dd-scroll-ps-48",
  "dd-scroll-pt-48",
  "dd-scroll-pr-48",
  "dd-scroll-pb-48",
  "dd-scroll-pl-48",

  "dd-scroll-p-52",
  "dd-scroll-px-52",
  "dd-scroll-py-52",
  "dd-scroll-ps-52",
  "dd-scroll-pt-52",
  "dd-scroll-pr-52",
  "dd-scroll-pb-52",
  "dd-scroll-pl-52",

  "dd-scroll-p-56",
  "dd-scroll-px-56",
  "dd-scroll-py-56",
  "dd-scroll-ps-56",
  "dd-scroll-pt-56",
  "dd-scroll-pr-56",
  "dd-scroll-pb-56",
  "dd-scroll-pl-56",

  "dd-scroll-p-60",
  "dd-scroll-px-60",
  "dd-scroll-py-60",
  "dd-scroll-ps-60",
  "dd-scroll-pt-60",
  "dd-scroll-pr-60",
  "dd-scroll-pb-60",
  "dd-scroll-pl-60",

  "dd-scroll-p-64",
  "dd-scroll-px-64",
  "dd-scroll-py-64",
  "dd-scroll-ps-64",
  "dd-scroll-pt-64",
  "dd-scroll-pr-64",
  "dd-scroll-pb-64",
  "dd-scroll-pl-64",

  "dd-scroll-p-72",
  "dd-scroll-px-72",
  "dd-scroll-py-72",
  "dd-scroll-ps-72",
  "dd-scroll-pt-72",
  "dd-scroll-pr-72",
  "dd-scroll-pb-72",
  "dd-scroll-pl-72",

  "dd-scroll-p-80",
  "dd-scroll-px-80",
  "dd-scroll-py-80",
  "dd-scroll-ps-80",
  "dd-scroll-pt-80",
  "dd-scroll-pr-80",
  "dd-scroll-pb-80",
  "dd-scroll-pl-80",

  "dd-scroll-p-96",
  "dd-scroll-px-96",
  "dd-scroll-py-96",
  "dd-scroll-ps-96",
  "dd-scroll-pt-96",
  "dd-scroll-pr-96",
  "dd-scroll-pb-96",
  "dd-scroll-pl-96",
];
