// import MyButton from './Button.vue';
import typography from "./index.vue"

// More on default export: https://storybook.js.org/docs/vue/writing-stories/introduction#default-export
export default {
    title: 'Example/typography',
    component: typography,
    // More on argTypes: https://storybook.js.org/docs/vue/api/argtypes
    argTypes: {

        title: {
            description: "Change title value as per the requirement",
            table: {
                defaultValue: {
                    summary: "Button"
                }
            }
        },
        class: {
            control: {
                type: 'select'
            },
            options: ["dd-text-xs",
                "dd-text-sm",
                "dd-text-base",
                "dd-text-lg",
                "dd-text-xl",
                "dd-text-2xl",
                "dd-text-3xl",
                "dd-text-4xl",
                "dd-text-5xl",
                "dd-text-6xl",
                "dd-text-7xl",
                "dd-text-8xl",
                "dd-text-9xl",
                "dd-font-thin",
                "dd-font-extralight",
                "dd-font-light",
                "dd-font-normal",
                "dd-font-medium",
                "dd-font-semibold",
                "dd-font-bold",
                "dd-font-extrabold",
                "dd-font-black",
                "dd-text-slate-50",
    "dd-text-slate-100",
    "dd-text-slate-200",
    "dd-text-slate-300",
    "dd-text-slate-400",
    "dd-text-slate-500",
    "dd-text-slate-600",
    "dd-text-slate-700",
    "dd-text-slate-800",
    "dd-text-slate-900",
    "dd-text-gray-50",
    "dd-text-gray-100",
    "dd-text-gray-200",
    "dd-text-gray-300",
    "dd-text-gray-400",
    "dd-text-gray-500",
    "dd-text-gray-600",
    "dd-text-gray-700",
    "dd-text-gray-800",
    "dd-text-gray-900",
    "dd-text-zinc-50",
    "dd-text-zinc-100",
    "dd-text-zinc-200",
    "dd-text-zinc-300",
    "dd-text-zinc-400",
    "dd-text-zinc-500",
    "dd-text-zinc-600",
    "dd-text-zinc-700",
    "dd-text-zinc-800",
    "dd-text-zinc-900",
    "dd-text-neutral-50",
    "dd-text-neutral-100",
    "dd-text-neutral-200",
    "dd-text-neutral-300",
    "dd-text-neutral-400",
    "dd-text-neutral-500",
    "dd-text-neutral-600",
    "dd-text-neutral-700",
    "dd-text-neutral-800",
    "dd-text-neutral-900",
    "dd-text-stone-50",
    "dd-text-stone-100",
    "dd-text-stone-200",
    "dd-text-stone-300",
    "dd-text-stone-400",
    "dd-text-stone-500",
    "dd-text-stone-600",
    "dd-text-stone-700",
    "dd-text-stone-800",
    "dd-text-stone-900",
    "dd-text-red-50",
    "dd-text-red-100",
    "dd-text-red-200",
    "dd-text-red-300",
    "dd-text-red-400",
    "dd-text-red-500",
    "dd-text-red-600",
    "dd-text-red-700",
    "dd-text-red-800",
    "dd-text-red-900",
    "dd-text-orange-50",
    "dd-text-orange-100",
    "dd-text-orange-200",
    "dd-text-orange-300",
    "dd-text-orange-400",
    "dd-text-orange-500",
    "dd-text-orange-600",
    "dd-text-orange-700",
    "dd-text-orange-800",
    "dd-text-orange-900",
    "dd-text-amber-50",
    "dd-text-amber-100",
    "dd-text-amber-200",
    "dd-text-amber-300",
    "dd-text-amber-400",
    "dd-text-amber-500",
    "dd-text-amber-600",
    "dd-text-amber-700",
    "dd-text-amber-800",
    "dd-text-amber-900",
    "dd-text-yellow-50",
    "dd-text-yellow-100",
    "dd-text-yellow-200",
    "dd-text-yellow-300",
    "dd-text-yellow-400",
    "dd-text-yellow-500",
    "dd-text-yellow-600",
    "dd-text-yellow-700",
    "dd-text-yellow-800",
    "dd-text-yellow-900",
    "dd-text-lime-50",
    "dd-text-lime-100",
    "dd-text-lime-200",
    "dd-text-lime-300",
    "dd-text-lime-400",
    "dd-text-lime-500",
    "dd-text-lime-600",
    "dd-text-lime-700",
    "dd-text-lime-800",
    "dd-text-lime-900",
    "dd-text-green-50",
    "dd-text-green-100",
    "dd-text-green-200",
    "dd-text-green-300",
    "dd-text-green-400",
    "dd-text-green-500",
    "dd-text-green-600",
    "dd-text-green-700",
    "dd-text-green-800",
    "dd-text-green-900",
    "dd-text-emerald-50",
    "dd-text-emerald-100",
    "dd-text-emerald-200",
    "dd-text-emerald-300",
    "dd-text-emerald-400",
    "dd-text-emerald-500",
    "dd-text-emerald-600",
    "dd-text-emerald-700",
    "dd-text-emerald-800",
    "dd-text-emerald-900",
    "dd-text-teal-50",
    "dd-text-teal-100",
    "dd-text-teal-200",
    "dd-text-teal-300",
    "dd-text-teal-400",
    "dd-text-teal-500",
    "dd-text-teal-600",
    "dd-text-teal-700",
    "dd-text-teal-800",
    "dd-text-teal-900",
    "dd-text-cyan-50",
    "dd-text-cyan-100",
    "dd-text-cyan-200",
    "dd-text-cyan-300",
    "dd-text-cyan-400",
    "dd-text-cyan-500",
    "dd-text-cyan-600",
    "dd-text-cyan-700",
    "dd-text-cyan-800",
    "dd-text-cyan-900",
    "dd-text-sky-50",
    "dd-text-sky-100",
    "dd-text-sky-200",
    "dd-text-sky-300",
    "dd-text-sky-400",
    "dd-text-sky-500",
    "dd-text-sky-600",
    "dd-text-sky-700",
    "dd-text-sky-800",
    "dd-text-sky-900",
    "dd-text-blue-50",
    "dd-text-blue-100",
    "dd-text-blue-200",
    "dd-text-blue-300",
    "dd-text-blue-400",
    "dd-text-blue-500",
    "dd-text-blue-600",
    "dd-text-blue-700",
    "dd-text-blue-800",
    "dd-text-blue-900",
    "dd-text-indigo-50",
    "dd-text-indigo-100",
    "dd-text-indigo-200",
    "dd-text-indigo-300",
    "dd-text-indigo-400",
    "dd-text-indigo-500",
    "dd-text-indigo-600",
    "dd-text-indigo-700",
    "dd-text-indigo-800",
    "dd-text-indigo-900",
    "dd-text-violet-50",
    "dd-text-violet-100",
    "dd-text-violet-200",
    "dd-text-violet-300",
    "dd-text-violet-400",
    "dd-text-violet-500",
    "dd-text-violet-600",
    "dd-text-violet-700",
    "dd-text-violet-800",
    "dd-text-violet-900",
    "dd-text-purple-50",
    "dd-text-purple-100",
    "dd-text-purple-200",
    "dd-text-purple-300",
    "dd-text-purple-400",
    "dd-text-purple-500",
    "dd-text-purple-600",
    "dd-text-purple-700",
    "dd-text-purple-800",
    "dd-text-purple-900",
    "dd-text-fuchsia-50",
    "dd-text-fuchsia-100",
    "dd-text-fuchsia-200",
    "dd-text-fuchsia-300",
    "dd-text-fuchsia-400",
    "dd-text-fuchsia-500",
    "dd-text-fuchsia-600",
    "dd-text-fuchsia-700",
    "dd-text-fuchsia-800",
    "dd-text-fuchsia-900",
    "dd-text-pink-50",
    "dd-text-pink-100",
    "dd-text-pink-200",
    "dd-text-pink-300",
    "dd-text-pink-400",
    "dd-text-pink-500",
    "dd-text-pink-600",
    "dd-text-pink-700",
    "dd-text-pink-800",
    "dd-text-pink-900",
    "dd-text-rose-50",
    "dd-text-rose-100",
    "dd-text-rose-200",
    "dd-text-rose-300",
    "dd-text-rose-400",
    "dd-text-rose-500",
    "dd-text-rose-600",
    "dd-text-rose-700",
    "dd-text-rose-800",
    "dd-text-rose-900",
    "dd-text-transparent",
    "dd-text-black",
    "dd-text-white",
              ],
            description: "Change color value as per the requirement primary / danger / success / white",
            table: {
                defaultValue: {
                    summary: "-"
                }
            }
        },
    },
};

// More on component templates: https://storybook.js.org/docs/vue/writing-stories/introduction#using-args
const Template = (args) => ({
    // Components used in your story `template` are defined in the `components` object
    components: { typography },
    setup() {
        return { args };

    },
    // The story's `args` need to be mapped into the template through the `setup()` method
    // And then the `args` are bound to your component with `v-bind="args"`
    template: '<typography  v-bind="args" />  ',
});



export const Index = Template.bind({});
// More on args: https://storybook.js.org/docs/vue/writing-stories/args
Index.args = {
    title: 'The face of the moon in shadow.',
    class: "dd-text-xl"
};


