const opacity = [
  "dd-opacity-0",
  "dd-opacity-5",
  "dd-opacity-10",
  "dd-opacity-20",
  "dd-opacity-25",
  "dd-opacity-30",
  "dd-opacity-40",
  "dd-opacity-50",
  "dd-opacity-60",
  "dd-opacity-70",
  "dd-opacity-75",
  "dd-opacity-80",
  "dd-opacity-90",
  "dd-opacity-95",
  "dd-opacity-100",
];
