const fontSize = [
  "dd-text-xs",
  "dd-text-sm",
  "dd-text-base",
  "dd-text-lg",
  "dd-text-xl",
  "dd-text-2xl",
  "dd-text-3xl",
  "dd-text-4xl",
  "dd-text-5xl",
  "dd-text-6xl",
  "dd-text-7xl",
  "dd-text-8xl",
  "dd-text-9xl",
];
