const backdropOpacity = [
  "dd-backdrop-opacity-0",
  "dd-backdrop-opacity-5",
  "dd-backdrop-opacity-10",
  "dd-backdrop-opacity-20",
  "dd-backdrop-opacity-25",
  "dd-backdrop-opacity-25",
  "dd-backdrop-opacity-30",
  "dd-backdrop-opacity-40",
  "dd-backdrop-opacity-50",
  "dd-backdrop-opacity-60",
  "dd-backdrop-opacity-70",
  "dd-backdrop-opacity-80",
  "dd-backdrop-opacity-90",
  "dd-backdrop-opacity-95",
  "dd-backdrop-opacity-100",
];
