<template>
  <svg
    width="17px"
    height="12px"
    viewBox="0 0 17 12"
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
  >
    <title>Icons/20px/Sort Ascending</title>
    <g
      id="☮️-Icons"
      stroke="none"
      stroke-width="1"
      fill="none"
      fill-rule="evenodd"
    >
      <g id="Icon-20px" transform="translate(-216.000000, -208.000000)">
        <g
          id="Icons/20px/Sort-Ascending"
          transform="translate(214.000000, 204.000000)"
        >
          <polygon id="Path" points="0 0 20 0 20 20 0 20"></polygon>
          <line
            x1="3.33333333"
            y1="5"
            x2="15.1666663"
            y2="5"
            id="Path"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          ></line>
          <line
            x1="3.33333333"
            y1="10"
            x2="10.1666663"
            y2="10"
            id="Path"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          ></line>
          <line
            x1="3.33333333"
            y1="15"
            x2="10.8333333"
            y2="15"
            id="Path"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          ></line>
          <polyline
            id="Path"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
            points="12.5 10.5 15 8 17.5 10.5"
          ></polyline>
          <line
            x1="15"
            y1="8"
            x2="15"
            y2="15"
            id="Path"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          ></line>
        </g>
      </g>
    </g>
  </svg>
</template>
