<template>
  <div>
    <!-- <dd-table :rows="rows" :columns="columnVal" :buttons="buttons" :Actions="Actions" :values="values" footer checkBoxProp
      fixedHeight rowKey="id" hoveringRow lastCell fixed actionHeader emptyState actionsPanel sortIcon settingbarIcon
      searchIcon @updateSettings="updateSettings" dragDrop /> -->
    <dd-tree :list="treeItem" :buttons="buttons" />
  </div>
</template>

<script setup>
import { ref } from "vue";
import DdTable from "./components/table/index.vue";
import DdTree from "./components/Tree/index.vue";


const buttons = ref([
  { id: 0, label: "button", color: "white", size: "16", icon: "" },
  { id: 1, label: "", color: "white", size: "16", icon: "Plus" },
  { id: 2, label: "", color: "white", size: "16", icon: "Pencil" },
  { id: 3, label: "", color: "white", size: "16", icon: "DotHorizontal" },
]);
const treeItem = ref([
  {
    id: 0,
    label: "All Categories",
    icon: "",
    checkbox: true,
    checked: true,
    badge: true,
    actions: true,
    disabled: false,
    count: "2345",
    children: [
      {
        id: 0,
        label: "Computer",
        icon: "",
        checkbox: true,
        checked: true,
        badge: true,
        actions: true,
        disabled: false,
        count: "100",
        children: [
          {
            id: 0,
            label: "Laptops",
            icon: "",
            checkbox: true,
            checked: true,
            badge: true,
            actions: true,
            disabled: false,
            count: "150",
            children: [
              {
                id: 0,
                label: "Macbook",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "300",
                children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [
                  {
                    id: 0,
                    label: "Pro",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Pro M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                ],
                  },
                  {
                    id: 0,
                    label: "Air M1",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "5",
                    children: [],
                  },
                ],
              },
              {
                id: 0,
                label: "PC",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "3",
                children: [
                  {
                    id: 0,
                    label: "XPS",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Zenbook",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Lenovo X1 Carbon",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 0,
            label: "Desktop",
            icon: "",
            checkbox: true,
            checked: true,
            badge: true,
            actions: true,
            disabled: false,
            count: "2",
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 1,
    label: "Mobile",
    icon: "",
    checkbox: true,
    checked: true,
    badge: true,
    actions: true,
    disabled: false,
    count: "50",
    children: [
      {
        id: 0,
        label: "Iphone",
        icon: "",
        checkbox: true,
        checked: true,
        badge: true,
        actions: true,
        disabled: false,
        count: "48",
        children: [
          {
            id: 0,
            label: "IphoneX and below...",
            icon: "",
            checkbox: true,
            checked: true,
            badge: true,
            actions: true,
            disabled: false,
            count: "24",
            children: [
              {
                id: 0,
                label: "Iphone X",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "16",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
              {
                id: 0,
                label: "Iphone 6",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "48",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 0,
            label: "Iphone 11 and above models",
            icon: "",
            checkbox: true,
            checked: true,
            badge: true,
            actions: true,
            disabled: false,
            count: "48",
            children: [],
          },
        ],
      },
      {
        id: 0,
        label: "Andriod",
        icon: "",
        checkbox: true,
        checked: true,
        badge: true,
        actions: true,
        disabled: false,
        count: "48",
        children: [],
      },
    ],
  },
  {
    id: 2,
    label: "Watch",
    icon: "",
    checkbox: true,
    checked: true,
    badge: true,
    actions: true,
    disabled: false,
    count: "48",
    children: [
      {
        id: 0,
        label: "Watch child",
        icon: "",
        checkbox: true,
        checked: true,
        badge: true,
        actions: true,
        disabled: false,
        count: "48",
        children: [],
      },
    ],
  },
]);
</script>


<style>
body {
  padding: 0;
  margin: 0;
  overflow-x: hidden !important;
}
</style>