<template>
  <div>
    <!-- <dd-table :rows="rows" :columns="columnVal" :buttons="buttons" :Actions="Actions" :values="values" footer checkBoxProp
      fixedHeight rowKey="id" hoveringRow lastCell fixed actionHeader emptyState actionsPanel sortIcon settingbarIcon
      searchIcon @updateSettings="updateSettings" dragDrop /> -->
    <dd-tree :list="treeItem" :buttons="buttons" />
  </div>
</template>

<script setup>
import { ref } from "vue";
import DdTable from "./components/table/index.vue";
import DdTree from "./components/Tree/index.vue";

const buttons = ref([
  // { id: 0, label: "button", color: "white", size: "16", icon: "" },
  { id: 1, label: "", color: "white", size: "16", icon: "Plus" },
  { id: 2, label: "", color: "white", size: "16", icon: "Pencil" },
  { id: 3, label: "", color: "white", size: "16", icon: "DotHorizontal" },
]);
const treeItem = ref([
  {
    id: 1,
    label: "All Categories",
    icon: "",
    checkbox: true,
    checked: true,
    badge: true,
    actions: true,
    disabled: false,
    count: "2345",
    children: [
      {
        id: 0,
        label: "Iphone",
        icon: "",
        checkbox: true,
        checked: true,
        badge: true,
        actions: true,
        disabled: false,
        count: "48",
        children: [
          {
            id: 0,
            label: "IphoneX and below...",
            icon: "",
            checkbox: true,
            checked: true,
            badge: true,
            actions: true,
            disabled: false,
            count: "24",
            children: [
              {
                id: 0,
                label: "Iphone X",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "16",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
                children: [
                  {
                    id: 0,
                    label: "Iphone X",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "16",
                    children: [
                      {
                        id: 0,
                        label: "Screen repair",
                        icon: "",
                        checkbox: true,
                        checked: true,
                        badge: true,
                        actions: true,
                        disabled: false,
                        count: "48",
                        children: [],
                      },
                      {
                        id: 0,
                        label: "Camera repair",
                        icon: "",
                        checkbox: true,
                        checked: true,
                        badge: true,
                        actions: true,
                        disabled: false,
                        count: "48",
                        children: [],
                      },
                      {
                        id: 0,
                        label: "Cleaning",
                        icon: "",
                        checkbox: true,
                        checked: true,
                        badge: true,
                        actions: true,
                        disabled: false,
                        count: "48",
                        children: [],
                      },
                      {
                        id: 0,
                        label: "Wifi signal issue",
                        icon: "",
                        checkbox: true,
                        checked: true,
                        badge: true,
                        actions: true,
                        disabled: false,
                        count: "48",
                        children: [],
                      },
                    ],
                  },
                  {
                    id: 0,
                    label: "Iphone 6",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [
                      {
                        id: 0,
                        label: "Screen repair",
                        icon: "",
                        checkbox: true,
                        checked: true,
                        badge: true,
                        actions: true,
                        disabled: false,
                        count: "48",
                        children: [],
                      },
                      {
                        id: 0,
                        label: "Camera repair",
                        icon: "",
                        checkbox: true,
                        checked: true,
                        badge: true,
                        actions: true,
                        disabled: false,
                        count: "48",
                        children: [],
                      },
                      {
                        id: 0,
                        label: "Cleaning",
                        icon: "",
                        checkbox: true,
                        checked: true,
                        badge: true,
                        actions: true,
                        disabled: false,
                        count: "48",
                        children: [],
                      },
                      {
                        id: 0,
                        label: "Wifi signal issue",
                        icon: "",
                        checkbox: true,
                        checked: true,
                        badge: true,
                        actions: true,
                        disabled: false,
                        count: "48",
                        children: [
                          {
                            id: 0,
                            label: "Iphone X",
                            icon: "",
                            checkbox: true,
                            checked: true,
                            badge: true,
                            actions: true,
                            disabled: false,
                            count: "16",
                            children: [
                              {
                                id: 0,
                                label: "Screen repair",
                                icon: "",
                                checkbox: true,
                                checked: true,
                                badge: true,
                                actions: true,
                                disabled: false,
                                count: "48",
                                children: [],
                              },
                              {
                                id: 0,
                                label: "Camera repair",
                                icon: "",
                                checkbox: true,
                                checked: true,
                                badge: true,
                                actions: true,
                                disabled: false,
                                count: "48",
                                children: [],
                              },
                              {
                                id: 0,
                                label: "Cleaning",
                                icon: "",
                                checkbox: true,
                                checked: true,
                                badge: true,
                                actions: true,
                                disabled: false,
                                count: "48",
                                children: [],
                              },
                              {
                                id: 0,
                                label: "Wifi signal issue",
                                icon: "",
                                checkbox: true,
                                checked: true,
                                badge: true,
                                actions: true,
                                disabled: false,
                                count: "48",
                                children: [],
                              },
                            ],
                          },
                          {
                            id: 0,
                            label: "Iphone 6",
                            icon: "",
                            checkbox: true,
                            checked: true,
                            badge: true,
                            actions: true,
                            disabled: false,
                            count: "48",
                            children: [
                              {
                                id: 0,
                                label: "Screen repair",
                                icon: "",
                                checkbox: true,
                                checked: true,
                                badge: true,
                                actions: true,
                                disabled: false,
                                count: "48",
                                children: [],
                              },
                              {
                                id: 0,
                                label: "Camera repair",
                                icon: "",
                                checkbox: true,
                                checked: true,
                                badge: true,
                                actions: true,
                                disabled: false,
                                count: "48",
                                children: [],
                              },
                              {
                                id: 0,
                                label: "Cleaning",
                                icon: "",
                                checkbox: true,
                                checked: true,
                                badge: true,
                                actions: true,
                                disabled: false,
                                count: "48",
                                children: [],
                              },
                              {
                                id: 0,
                                label: "Wifi signal issue",
                                icon: "",
                                checkbox: true,
                                checked: true,
                                badge: true,
                                actions: true,
                                disabled: false,
                                count: "48",
                                children: [],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              {
                id: 0,
                label: "Iphone 6",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "48",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [
              {
                id: 0,
                label: "Iphone X",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "16",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
              {
                id: 0,
                label: "Iphone 6",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "48",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [
              {
                id: 0,
                label: "Iphone X",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "16",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
              {
                id: 0,
                label: "Iphone 6",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "48",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
            ],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
            ],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 0,
            label: "Iphone 11 and above models",
            icon: "",
            checkbox: true,
            checked: true,
            badge: true,
            actions: true,
            disabled: false,
            count: "48",
            children: [],
          },
        ],
      },
      {
        id: 0,
        label: "Andriod",
        icon: "",
        checkbox: true,
        checked: true,
        badge: true,
        actions: true,
        disabled: false,
        count: "48",
        children: [
          {
            id: 0,
            label: "IphoneX and below...",
            icon: "",
            checkbox: true,
            checked: true,
            badge: true,
            actions: true,
            disabled: false,
            count: "24",
            children: [
              {
                id: 0,
                label: "Iphone X",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "16",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
              {
                id: 0,
                label: "Iphone 6",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "48",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 0,
            label: "Iphone 11 and above models",
            icon: "",
            checkbox: true,
            checked: true,
            badge: true,
            actions: true,
            disabled: false,
            count: "48",
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 1,
    label: "Mobile",
    icon: "",
    checkbox: true,
    checked: true,
    badge: true,
    actions: true,
    disabled: false,
    count: "50",
    children: [
      {
        id: 0,
        label: "Iphone",
        icon: "",
        checkbox: true,
        checked: true,
        badge: true,
        actions: true,
        disabled: false,
        count: "48",
        children: [
          {
            id: 0,
            label: "IphoneX and below...",
            icon: "",
            checkbox: true,
            checked: true,
            badge: true,
            actions: true,
            disabled: false,
            count: "24",
            children: [
              {
                id: 0,
                label: "Iphone X",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "16",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
              {
                id: 0,
                label: "Iphone 6",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "48",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 0,
            label: "Iphone 11 and above models",
            icon: "",
            checkbox: true,
            checked: true,
            badge: true,
            actions: true,
            disabled: false,
            count: "48",
            children: [],
          },
        ],
      },
      {
        id: 0,
        label: "Andriod",
        icon: "",
        checkbox: true,
        checked: true,
        badge: true,
        actions: true,
        disabled: false,
        count: "48",
        children: [
          {
            id: 0,
            label: "IphoneX and below...",
            icon: "",
            checkbox: true,
            checked: true,
            badge: true,
            actions: true,
            disabled: false,
            count: "24",
            children: [
              {
                id: 0,
                label: "Iphone X",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "16",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
              {
                id: 0,
                label: "Iphone 6",
                icon: "",
                checkbox: true,
                checked: true,
                badge: true,
                actions: true,
                disabled: false,
                count: "48",
                children: [
                  {
                    id: 0,
                    label: "Screen repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Camera repair",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Cleaning",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                  {
                    id: 0,
                    label: "Wifi signal issue",
                    icon: "",
                    checkbox: true,
                    checked: true,
                    badge: true,
                    actions: true,
                    disabled: false,
                    count: "48",
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 0,
            label: "Iphone 11 and above models",
            icon: "",
            checkbox: true,
            checked: true,
            badge: true,
            actions: true,
            disabled: false,
            count: "48",
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    label: "Watch",
    icon: "",
    checkbox: true,
    checked: true,
    badge: true,
    actions: true,
    disabled: false,
    count: "48",
    children: [
      {
        id: 0,
        label: "Watch child",
        icon: "",
        checkbox: true,
        checked: true,
        badge: true,
        actions: true,
        disabled: false,
        count: "48",
        children: [],
      },
    ],
  },
]);
</script>


<style>
body {
  padding: 0;
  margin: 0;
  overflow-x: hidden !important;
}
</style>